[workspace]
members = [
    "crates/client/core",
    "crates/client/cli",
    "crates/client/desktop-app/src-tauri",
    "crates/server"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Balcus Bogdan <bbalcus04@gmail.com>"]