[package]
name = "proto"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
prost = "0.13"
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
prost-build = "0.13"
protoc-bin-vendored = "3"