[package]
name = "flux_server"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
proto = { path = "../proto" }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.12", features = ["transport"] }
async-trait = "0.1"